### ISSUE TITLE
module error in Paired and One Sample T-Test.

### ISSUE THREAD

**Issue by MAgojam** [richarddmorey/jpower#13]
Hi @richarddmorey,
I have already reported this in jamovi forum "Module development", but maybe it's better here?
Checking the Type I error, always for "Paired Samples T-Test" and "One Sample T-Test", using 0.005 2-tailed, (N is calculated correctly) but error message appears and the selected plots are not displayed. :thinking: 

I am attaching screenshots that also includes G*Power output.
![jpower_2tailed](https://user-images.githubusercontent.com/36552289/40301728-4069db6e-5ced-11e8-9d7f-e1183f82be80.PNG)

Thanks for this module, I like it and I hope you will continue to support it with new entries.

Cheers,
Maurizio

**Comment by richarddmorey** [comment]
Confirmed; looks like an numerical optimization issue. I'll follow it up; thanks for the report.

**Comment by richarddmorey** [comment]
Traced this back to an issue in the R pwr package. I've raised the issue here:

https://github.com/heliosdrm/pwr/issues/19

If the authors of pwr are slow, we can implement a workaround. I believe the new version has a temporary fix for it, so if you update jpower, you shouldn't get the error.
