### ISSUE TITLE
Independent Samples T-Test issue

### ISSUE THREAD

**Issue by dropmann** [richarddmorey/jpower#16]
Hi Richard,

If a power of 1 is entered it puts something into an infinite loop and jamovi even has difficulty closing. It seems to only be an issue in Independent Samples T-Test. The others throw an error. Could put a limit on the textbox but the analysis should probably throw an error as well.

**Comment by richarddmorey** [comment]
Interesting; seems reasonable (both a limit on the textbox and on the analysis). I'll investigate and figure out where best to do it.

**Comment by richarddmorey** [comment]
I've added a check for power>=1 in my custom function, but now I need to set up all the jamovi development stuff to test. If you have it all set up, could you give this commit a test run?

**Comment by richarddmorey** [comment]
Fixed and committed.
