### ISSUE TITLE
Run analyses in R

### ISSUE THREAD

**Issue by benjaminwnelson** [richarddmorey/jpower#17]
Does jpower work in R? Jamovi shows syntax, but I can't find a way to download the package. Thanks!

**Comment by richarddmorey** [comment]
I think this is one for @jonathon-love or @raviselker

**Comment by jonathon-love** [comment]
i'm not sure if it will work, but you're welcome to try.

```
remotes::install_github('richarddmorey/jpower', subdir='jpower')
```

**Comment by benjaminwnelson** [comment]
That worked. Thank you!
